name: build docs
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: building
        uses: ZanderZhao/gitbook-action@v1.2.4
        with:
          source_branch: docs
          source_edit_time: true
          token: ${{ secrets.GITBOOK_ACTION_TOKEN }}
          publish_push_force: true
          publish_commit_history: false # just last commit
          publish_commit_message: ${{ github.event.head_commit.message }}
          publish_cname: openingo.org
          gitbook_pdf: true
          gitbook_pdf_dir: books
          gitbook_pdf_name: godkits
          gitbook_epub: true
          gitbook_epub_dir: books
          gitbook_epub_name: godkits
          gitbook_mobi: true
          gitbook_mobi_dir: books
          gitbook_mobi_name: godkits
          font_install: sudo apt-get install fonts-noto-cjk
          
          

